export const allLanguages = [
    { "id": 1, "code": "af", "language": "Afrikaans" },
    { "id": 2, "code": "sq", "language": "Albanian" },
    { "id": 3, "code": "am", "language": "Amharic" },
    { "id": 4, "code": "ar", "language": "Arabic" },
    { "id": 5, "code": "hy", "language": "Armenian" },
    { "id": 6, "code": "as", "language": "Assamese" },
    { "id": 7, "code": "ay", "language": "Aymara" },
    { "id": 8, "code": "az", "language": "Azerbaijani" },
    { "id": 9, "code": "bm", "language": "Bambara" },
    { "id": 10, "code": "eu", "language": "Basque" },
    { "id": 11, "code": "be", "language": "Belarusian" },
    { "id": 12, "code": "bn", "language": "Bengali" },
    { "id": 13, "code": "bho", "language": "Bhojpuri" },
    { "id": 14, "code": "bs", "language": "Bosnian" },
    { "id": 15, "code": "bg", "language": "Bulgarian" },
    { "id": 16, "code": "ca", "language": "Catalan" },
    { "id": 17, "code": "ceb", "language": "Cebuano" },
    { "id": 18, "code": "zh-CN", "language": "Chinese (Simplified)" },
    { "id": 19, "code": "zh-TW", "language": "Chinese (Traditional)" },
    { "id": 20, "code": "co", "language": "Corsican" },
    { "id": 21, "code": "hr", "language": "Croatian" },
    { "id": 22, "code": "cs", "language": "Czech" },
    { "id": 23, "code": "da", "language": "Danish" },
    { "id": 24, "code": "dv", "language": "Dhivehi" },
    { "id": 25, "code": "doi", "language": "Dogri" },
    { "id": 26, "code": "nl", "language": "Dutch" },
    { "id": 27, "code": "en", "language": "English" },
    { "id": 28, "code": "eo", "language": "Esperanto" },
    { "id": 29, "code": "et", "language": "Estonian" },
    { "id": 30, "code": "ee", "language": "Ewe" },
    { "id": 31, "code": "fil", "language": "Filipino (Tagalog)" },
    { "id": 32, "code": "fi", "language": "Finnish" },
    { "id": 33, "code": "fr", "language": "French" },
    { "id": 34, "code": "fy", "language": "Frisian" },
    { "id": 35, "code": "gl", "language": "Galician" },
    { "id": 36, "code": "ka", "language": "Georgian" },
    { "id": 37, "code": "de", "language": "German" },
    { "id": 38, "code": "el", "language": "Greek" },
    { "id": 39, "code": "gn", "language": "Guarani" },
    { "id": 40, "code": "gu", "language": "Gujarati" },
    { "id": 41, "code": "ht", "language": "Haitian Creole" },
    { "id": 42, "code": "ha", "language": "Hausa" },
    { "id": 43, "code": "haw", "language": "Hawaiian" },
    { "id": 44, "code": "he", "language": "Hebrew" },
    { "id": 45, "code": "hi", "language": "Hindi" },
    { "id": 46, "code": "hmn", "language": "Hmong" },
    { "id": 47, "code": "hu", "language": "Hungarian" },
    { "id": 48, "code": "is", "language": "Icelandic" },
    { "id": 49, "code": "ig", "language": "Igbo" },
    { "id": 50, "code": "ilo", "language": "Ilocano" },
    { "id": 51, "code": "id", "language": "Indonesian" },
    { "id": 52, "code": "ga", "language": "Irish" },
    { "id": 53, "code": "it", "language": "Italian" },
    { "id": 54, "code": "ja", "language": "Japanese" },
    { "id": 55, "code": "jv", "language": "Javanese" },
    { "id": 56, "code": "kn", "language": "Kannada" },
    { "id": 57, "code": "kk", "language": "Kazakh" },
    { "id": 58, "code": "km", "language": "Khmer" },
    { "id": 59, "code": "rw", "language": "Kinyarwanda" },
    { "id": 60, "code": "gom", "language": "Konkani" },
    { "id": 61, "code": "ko", "language": "Korean" },
    { "id": 62, "code": "kri", "language": "Krio" },
    { "id": 63, "code": "ku", "language": "Kurdish" },
    { "id": 64, "code": "ckb", "language": "Kurdish (Sorani)" },
    { "id": 65, "code": "ky", "language": "Kyrgyz" },
    { "id": 66, "code": "lo", "language": "Lao" },
    { "id": 67, "code": "la", "language": "Latin" },
    { "id": 68, "code": "lv", "language": "Latvian" },
    { "id": 69, "code": "ln", "language": "Lingala" },
    { "id": 70, "code": "lt", "language": "Lithuanian" },
    { "id": 71, "code": "lg", "language": "Luganda" },
    { "id": 72, "code": "lb", "language": "Luxembourgish" },
    { "id": 73, "code": "mk", "language": "Macedonian" },
    { "id": 74, "code": "mai", "language": "Maithili" },
    { "id": 75, "code": "mg", "language": "Malagasy" },
    { "id": 76, "code": "ms", "language": "Malay" },
    { "id": 77, "code": "ml", "language": "Malayalam" },
    { "id": 78, "code": "mt", "language": "Maltese" },
    { "id": 79, "code": "mi", "language": "Maori" },
    { "id": 80, "code": "mr", "language": "Marathi" },
    { "id": 81, "code": "mni-Mtei", "language": "Meiteilon (Manipuri)" },
    { "id": 82, "code": "lus", "language": "Mizo" },
    { "id": 83, "code": "mn", "language": "Mongolian" },
    { "id": 84, "code": "my", "language": "Myanmar (Burmese)" },
    { "id": 85, "code": "ne", "language": "Nepali" },
    { "id": 86, "code": "no", "language": "Norwegian" },
    { "id": 87, "code": "ny", "language": "Nyanja (Chichewa)" },
    { "id": 88, "code": "or", "language": "Odia (Oriya)" },
    { "id": 89, "code": "om", "language": "Oromo" },
    { "id": 90, "code": "ps", "language": "Pashto" },
    { "id": 91, "code": "fa", "language": "Persian" },
    { "id": 92, "code": "pl", "language": "Polish" },
    { "id": 93, "code": "pt", "language": "Portuguese" },
    { "id": 94, "code": "pa", "language": "Punjabi" },
    { "id": 95, "code": "qu", "language": "Quechua" },
    { "id": 96, "code": "ro", "language": "Romanian" },
    { "id": 97, "code": "ru", "language": "Russian" },
    { "id": 98, "code": "sm", "language": "Samoan" },
    { "id": 99, "code": "sa", "language": "Sanskrit" },
    { "id": 100, "code": "gd", "language": "Scots Gaelic" },
    { "id": 101, "code": "nso", "language": "Sepedi" },
    { "id": 102, "code": "sr", "language": "Serbian" },
    { "id": 103, "code": "st", "language": "Sesotho" },
    { "id": 104, "code": "sn", "language": "Shona" },
    { "id": 105, "code": "sd", "language": "Sindhi" },
    { "id": 106, "code": "si", "language": "Sinhala (Sinhalese)" },
    { "id": 107, "code": "sk", "language": "Slovak" },
    { "id": 108, "code": "sl", "language": "Slovenian" },
    { "id": 109, "code": "so", "language": "Somali" },
    { "id": 110, "code": "es", "language": "Spanish" },
    { "id": 111, "code": "su", "language": "Sundanese" },
    { "id": 112, "code": "sw", "language": "Swahili" },
    { "id": 113, "code": "sv", "language": "Swedish" },
    { "id": 114, "code": "tl", "language": "Tagalog" },
    { "id": 115, "code": "tg", "language": "Tajik" },
    { "id": 116, "code": "ta", "language": "Tamil" },
    { "id": 117, "code": "tt", "language": "Tatar" },
    { "id": 118, "code": "te", "language": "Telugu" },
    { "id": 119, "code": "th", "language": "Thai" },
    { "id": 120, "code": "ti", "language": "Tigrinya" },
    { "id": 121, "code": "ts", "language": "Tsonga" },
    { "id": 122, "code": "tr", "language": "Turkish" },
    { "id": 123, "code": "tk", "language": "Turkmen" },
    { "id": 124, "code": "ak", "language": "Twi (Akan)" },
    { "id": 125, "code": "uk", "language": "Ukrainian" },
    { "id": 126, "code": "ur", "language": "Urdu" },
    { "id": 127, "code": "ug", "language": "Uyghur" },
    { "id": 128, "code": "uz", "language": "Uzbek" },
    { "id": 129, "code": "vi", "language": "Vietnamese" },
    { "id": 130, "code": "cy", "language": "Welsh" },
    { "id": 131, "code": "xh", "language": "Xhosa" },
    { "id": 132, "code": "yi", "language": "Yiddish" },
    { "id": 133, "code": "yo", "language": "Yoruba" },
    { "id": 134, "code": "zu", "language": "Zulu" }
];

export const listOfLandmarks = [
    { name: "Crkva sv. Marka", latitude: 45.8163, longitude: 15.9732, description: "Crkva iz 13. stoljeća poznata po šarenom krovu s grbovima Zagreba i Hrvatske." },
    { name: "Zagrebačka katedrala", latitude: 45.8144, longitude: 15.9770, description: "Najviša zgrada u Hrvatskoj iz 13. stoljeća s gotičkom arhitekturom i ikoničnim dvostrukim tornjevima." },
    { name: "Kula Lotrščak", latitude: 45.8163, longitude: 15.9784, description: "Povijesna kula iz 13. stoljeća koja nudi panoramski pogled na Zagreb, smještena u Gornjem gradu." },
    { name: "Kamenita vrata", latitude: 45.8175, longitude: 15.9758, description: "Povijesna vrata iz 13. stoljeća koja danas čuvaju svetište s poštovanom slikom Djevice Marije." },
    { name: "Trg bana Jelačića", latitude: 45.8125, longitude: 15.9770, description: "Centralni trg Zagreba, nazvan po Banu Josipu Jelačiću, hrvatskom vojnom vođi, s kipom u njegovu čast." },
    { name: "Dolac", latitude: 45.8150, longitude: 15.9779, description: "Glavni otvoreni tržnica u Zagrebu, datira iz 20. stoljeća, poznat po svježem voću, povrću, cvijeću i lokalnim proizvodima." },
    { name: "Mirogoj", latitude: 45.8314, longitude: 15.9833, description: "Monumentalno groblje, smatra se jednim od najljepših u Europi, s arkadama, skulpturama i uređenim vrtovima." },
    { name: "Hrvatsko narodno kazalište", latitude: 45.8129, longitude: 15.9783, description: "Povijesno kazalište iz kasnog 19. stoljeća, poznato po neo-baroknoj arhitekturi i predstavama." },
    { name: "Muzej grada Zagreba", latitude: 45.8160, longitude: 15.9753, description: "Muzej smješten u povijesnoj zgradi, predstavlja povijest i kulturu Zagreba kroz različite izloške i artefakte." },
    { name: "Hrvatski sabor", latitude: 45.8083, longitude: 15.9777, description: "Sjedište Hrvatskog sabora, impozantna neoklasična zgrada izgrađena krajem 19. stoljeća." },
    { name: "Umjetnički paviljon u Zagrebu", latitude: 45.8127, longitude: 15.9792, description: "Umjetnička galerija izgrađena za Budimpeštansku izložbu 1895., s privremenim izložbama suvremene umjetnosti." },
    { name: "Botanički vrt u Zagrebu", latitude: 45.8217, longitude: 15.9734, description: "Jedan od najstarijih botaničkih vrtova u Europi, s raznovrsnom zbirkom biljaka i staklenicima." },
    { name: "Muzej prekinutih veza", latitude: 45.8155, longitude: 15.9780, description: "Jedinstveni muzej posvećen propalim vezama, prikazuje osobne predmete i priče donirane od pojedinaca diljem svijeta." },
    { name: "Park Maksimir", latitude: 45.8236, longitude: 16.0310, description: "Najstariji javni park u Zagrebu, s pitoresknim šetnicama, jezerima i zoološkim vrtom." },
    { name: "Zagrebačka uspinjača", latitude: 45.8137, longitude: 15.9757, description: "Jedna od najkraćih uspinjača na svijetu, povezuje Gornji i Donji grad Zagreba od 1890. godine." },
    { name: "Muzej iluzija", latitude: 45.8136, longitude: 15.9761, description: "Interaktivni muzej koji nudi optičke iluzije, holograme i zapanjujuće izloške." },
    { name: "Jarun", latitude: 45.7871, longitude: 15.9366, description: "Popularno rekreacijsko područje s velikim jezerom za aktivnosti poput plivanja, veslanja i vožnje biciklom." },
    { name: "Trg kralja Tomislava", latitude: 45.8087, longitude: 15.9776, description: "Mistični trg s kipom kralja Tomislava, prvog hrvatskog kralja." },
    { name: "Hrvatski muzej naivne umjetnosti", latitude: 45.8152, longitude: 15.9760, description: "Muzej posvećen naivnoj umjetnosti, prikazuje radove samoukih umjetnika iz Hrvatske i šire." },
    { name: "Zagreb Eye", latitude: 45.8122, longitude: 15.9778, description: "Promatračka platforma koja nudi panoramski pogled na zagrebački horizont i znamenitosti." },
    { name: "Tkalčićeva ulica", latitude: 45.8134, longitude: 15.9775, description: "Živahna pješačka ulica s kafićima, restoranima i trgovinama, poznata po svojoj vibrantnoj atmosferi." },
    { name: "Muzej suvremene umjetnosti", latitude: 45.7989, longitude: 15.9666, description: "Najveći muzej suvremene umjetnosti u Hrvatskoj, s raznolikom zbirkom modernih i avangardnih djela." },
    { name: "Hrvatski željeznički muzej", latitude: 45.8128, longitude: 15.9880, description: "Muzej koji prikazuje povijest željeznica u Hrvatskoj, s vintage lokomotivama, vagonima i artefaktima." }
];

export const categories = [
    { id: 2, category: 'historical'},
    { id: 3, category: 'architectural'},
    { id: 4, category: 'natural'},
    { id: 5, category: 'cultural'},
]